[package]
name = "zettabgp"
version = "0.3.5"
authors = ["Vladimir Melnikov <wlad.w.m@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/wladwm/zettabgp"
keywords = ["BGP"]
categories = ["network-programming","encoding","data-structures"]
description = "This is a BGP (parsing and composing) and BMP (only parsing) protocols driver library for Rust"
readme = "README.md"

[features]
default = ["serialization"]
serialization = ["serde"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
serde = { version="1.0", features = ["derive"], optional = true }

[dev-dependencies]
env_logger = "0.10.0"

